.\"
.\" Manpage of rrc command
.\"  Copyright 2023 Hiroyuki Kikuchi (hjfk07@gmail.com)
.\"
.\"	@(#)rrc.1
.\"
.TH rrc 1 "Janualy 5, 2023"
.SH NAME
rrc \- return return code.

.SH SYNOPSIS
.B rrc
[
.I return_code
]
.SH DESCRIPTION
This command returns a specified return code (exit code).
This command may be useful for checking exit codes.

.SH EXIT STATUS
when no arguments : returns 0
.PP
when more than 2 arguments : returns 1
.PP
when 1 argument : convert argument to integer and return it as a return code.

.SH EXAMPLES
.PP
.RS 6
$ rrc
.PP
$ echo $?
.RE
.PP
Return code is 0. 
.PP
.RS 6
$ rrc 1 2
.RE
.PP
Return code is 1. Because of too many arguments.
.PP
.RS 6
$ rrc -1
.RE
.PP
Return code is -1.
.PP
Note: According to UNIX system, exit code is defined between 0 to 255. See wait(3) and/or wait(2).
So using rrc as a child process, this will return 255 instead of -1, it depends on the parent process.
.PP

.SH SEE ALSO
wait(3), wait(2)

.SH AUTHOR
Hiroyuki Kikuchi (hjfk07@gmail.com)

.SH MORE DETAILS
UNIX command A command that returns an arbitrary return code (exit code): rrc
.URL https://hilog07.blogspot.com/2023/01/unix-rrc.html "Open Link"
.UR https://hilog07.blogspot.com/2023/01/unix-rrc.html
.UE
